In [1]:
import numpy as np

a = [3,4,1.2, '3']
b = np.array(a, dtype=int)
print(b)

[3 4 1 3]


In [2]:
# 
c = np.ones(11, dtype= int)
d = np.zeros(11, dtype = int)
e = np.ones((4,4), dtype= int)
print(c)
print(d)
print(e)

c =np.empty(10) # creates empty none items of size given
f = np.full((3,3),4)

print(c)
print(f)

[1 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [3]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.arange(2,21,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
z = np.linspace(2,20)
z

a = np.linspace(2,10,5, dtype=int)
print(a)

[ 2  4  6  8 10]


In [6]:
 d  = np.identity(3)
print(d) # identity Matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
a = np.eye(3,4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [8]:
b = np.random.rand(4)
print(b)

[0.8701649  0.23571323 0.31164913 0.47160583]


In [9]:
print(np.random.rand(2,3))
print()
print(np.random.rand(2,3)*10)

[[0.53915352 0.64923611 0.07671029]
 [0.95267953 0.74851015 0.86186333]]

[[7.12614337 1.68577128 2.02143024]
 [2.60502618 3.04127346 7.02535659]]


In [11]:
import numpy as np

arr = np.arange(11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [14]:
print(arr.data)
print(arr.shape)
print(arr.strides) # 8 bytes one element
print(arr.dtype)

(11,)
(8,)
int64


In [18]:
arr = np.ones((3,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
print(arr.data)
print(arr.shape)
print(arr.strides) #  bytes one element here is it is different.
print(arr.dtype)

(3, 3)
(24, 8)
int64


In [27]:
# we cannot have list slicing for 2D arrays
# but for NP 2D arrays we can do the slicings

In [32]:
a = np.random.randint(1,20,5)
print(a)

b = np.random.randint(2,22,5)


a = a+1
print (a)

[12  7 11  1  8]
[13  8 12  2  9]


In [35]:
li = [i for i in range(10)]
print(li)
li = [i+1 for i in li]
print(li)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [38]:
# we can directly do 
print(a-b)
print(a+b)
print(a/b)
print(a*b)
print(a//b)
print(a**b)
# for np arrays


[ 9  0 -5 -8 -8]
[17 16 29 12 26]
[3.25       1.         0.70588235 0.2        0.52941176]
[ 52  64 204  20 153]
[3 1 0 0 0]
[     28561   16777216          0       1024 -217042295]


In [41]:
print(a.argmin()) # gives index of min element
print(a.argmax()) # gives index of max element
print(a.mean())   # gives the average

3
0
8.8


In [44]:
# we can do even relational and logical operations on NP arrays directly 

In [49]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))
print(np.logical_not(a,b))

[ True  True  True  True  True]
[False False False False False]
[0 0 0 0 0]


In [74]:
# using bool indexing

ar = np.random.randint(1,20,8)

bool_arr = ar > 10
print(bool_arr)
final_arr = ar[bool_arr]
print(final_arr)

bool_fi = ar[ar>10] # we can write the same thing like this
print(bool_fi)

[ True False  True  True False False  True False]
[19 17 19 16]
[19 17 19 16]


In [90]:
abc = np.array([1,2,3,10,10,10,10])
idx = (np.where(abc==10))
print(idx)

(array([3, 4, 5, 6]),)


In [93]:
a = np.random.randint(1,30, (5,6))
print(a)

[[12  8 27 13  7 17]
 [ 2  4 26 24 11  4]
 [18  8 25  8  7 22]
 [ 4 23 23 14 23 15]
 [23 18 21 14 20 21]]


In [101]:
dd_array = a>20

In [103]:
a[dd_array] = 100
print(a)

[[ 12   8 100  13   7  17]
 [  2   4 100 100  11   4]
 [ 18   8 100   8   7 100]
 [  4 100 100  14 100  15]
 [100  18 100  14  20 100]]


In [105]:
## BroadCasting
abb = np.random.randint(1,10,(3,3))
bbb = np.random.randint(1,20,(3,3))
print(abb + bbb)  

[[19 24 18]
 [ 6 14  4]
 [23 19 14]]


In [109]:

abb = np.random.randint(1,10,(3,3))
print(abb)
bbb = np.random.randint(1,20,(3))
print(bbb)
print(abb + bbb) # broadcasting is hapening internally, 

[[2 1 1]
 [1 7 8]
 [4 6 2]]
[3 9 3]
[[ 5 10  4]
 [ 4 16 11]
 [ 7 15  5]]


In [120]:
# other methods
print(abb)
abb=np.resize(abb,(4,4))
abb =np.transpose(abb)
# np.reshape(abb, (4,4))
print(abb)

[[2 1 4]
 [1 7 6]
 [1 8 2]]
[[2 7 2 1]
 [1 6 2 7]
 [4 1 1 6]
 [1 8 4 1]]
